apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web3-assets.fullname" . }}
  labels:
    {{- include "web3-assets.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "web3-assets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "web3-assets.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "web3-assets.serviceAccountName" . }}
      initContainers:
      - name: sync drive
        image: "{{ .Values.rclone.image.repository }}:{{ .Values.rclone.image.version }}"
        args: ["rclone" "copy" "drive:" "/assets"]
        volumeMounts:
        - name: config-volume
          mountPath: /root/.config/rclone/rclone.conf
        - name: data-volume
          mountPath: /assets
        command: ['sh', '-c', "rclone sync --progress drive: /assets"]
      volumes:
      - name: config-volume
        secret:
          secretName: {{ include "web3-assets.fullname" . }}-config
{{ if eq .Values.environment "ci" }}
      - name: data-volume
        emptyDir: {}
{{ else }}
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 100Gi
{{ end }}
