version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/assets .
  chartLint:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - run:
          description: helm lint
          command: |
            helm lint ./charts/assets
      - run:
          description: helm template
          command: |
            helm template ./charts/assets
  publishImage:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/assets
  publishChart:
    docker:
      - image: web3f/ci-commons:2.1.4
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh web3f/assets
  deploy:
    docker:
      - image: web3f/ci-commons:v2.1.4
    steps:
      - checkout
      - run:
          command: |
            ./scripts/deploy.sh
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - chartLint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
            - chartLint
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishImage
            - publishChart
