{{ if eq .Values.environment "production" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
{{ end }}
