{{ if eq .Values.environment "ci" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
{{ end }}
