apiVersion: v1
kind: Secret
metadata:
  name: {{ include "assets.fullname" . }}-config
data:
  driveName: {{ .Values.rclone.config.driveName  | default  "drive" | b64enc }}
  scope: {{ .Values.rclone.config.scope  | default  "readonly" | b64enc }}
  rootFolderID: {{ .Values.rclone.config.rootFolderID  | default  "" | b64enc }}
  token: {{ .Values.rclone.config.token  | default  "TOKEN" | b64enc }}
  github: {{ .Values.rclone.config.github  | default  "GITHUB TOKEN" | b64enc }}
