apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "assets.fullname" . }}
  labels:
    {{- include "assets.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "assets.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "assets.fullname" . }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "assets.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version | default .Chart.AppVersion }}"
          env:
            - name: DRIVE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "assets.fullname" . }}-config
                  key: driveName
            - name: DRIVE_SCOPE
              valueFrom:
                secretKeyRef:
                  name: {{ include "assets.fullname" . }}-config
                  key: scope
            - name: ROOT_FOLDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "assets.fullname" . }}-config
                  key: rootFolderID
            - name: DRIVE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "assets.fullname" . }}-config
                  key: token
            - name: GITHUB_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "assets.fullname" . }}-config
                  key: github
          volumeMounts:
          - name: assets-data-volume
            mountPath: /assets
  volumeClaimTemplates:
  - metadata:
      name: assets-data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
{{ if eq .Values.environment "ci" }}
          storage: 1Gi
{{ else }}
          storage: 50Gi
{{ end }}
