environments:
  production:
  ci:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: assets
  namespace: assets
{{ if eq .Environment.Name "production" }}
  chart: w3f/assets
{{ else }}
  chart: ../charts/assets
{{ end }}
  values:
  - ./config/assets-values.yaml.gotmpl
