environment: production
replicaCount: 1

image:
  repository: web3f/assets-share
  version: v0.0.1
  pullPolicy: IfNotPresent

rclone:
  config: "a2xzZGpsYWpkcw=="

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
