environment: production
replicaCount: 1

image:
  repository: web3f/assets
  version: v0.0.2
  pullPolicy: IfNotPresent

rclone:
  config:
    driveName:
    scope:
    rootFolderID:
    token:
    github:

statefulset:
  updateStrategy: RollingUpdate

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
